# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17a_7GTHJSN8pDrj-Stw4tXXNMTK-7Pjs
"""

import pandas as pd
df = pd.read_csv("customer_shopping_behavior.csv")

df.head()

df.describe(include='all')

df.describe(include='all')

df.describe(include='all')

df.info()

df.describe(include='all')

df.info()

df.describe(include='all')

df.isnull()

df.isnull().sum() #adding the missing values from different attributes

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

df.columns

#Creates a new column to understand the age group
labels = ['Young Adult','Adult','Middle-Aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

df[['age','age_group']].head(10)

# using map function for a new variable 'freuency_mapping' to segreggate number of purchase days into english day labels
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Every 3 Months' : 90,
    'Quarterly': 90,
    'Bi-Weekly' : 14,
    'Annually' : 365

}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['frequency_of_purchases','purchase_frequency_days']].head(10)

df[['discount_applied', 'promo_code_used']].head(10)

(df['discount_applied'] == df['promo_code_used']).all()

df = df.drop('promo_code_used', axis=1)

df.columns

 



from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "kiit" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behaviour"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")


# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

